name 'fast-elk'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Instalfast-elk/Configures fast-elk'
long_description 'Instalfast-elk/Configures fast-elk'
version '0.1.7'

depends 'nginx'
depends 'java'
depends 'ark'
depends 'nxlog'
depends 'chocolatey'
